data_sources:
  interview_questions:
    description: "Sources used to generate interview-style questions"
    raw:
      - name: kaggle
        type: public_datset
        files:
          - deeplearning_questions.csv
          - interview_question_bank.csv
        local_path: data/datasets/raw/interview_questions
      - name: github
        type: repository
        urls:
          - https://raw.githubusercontent.com/alexeygrigorev/data-science-interviews/refs/heads/master/theory.md
        local_path: data/datasets/raw/interview_questions
    processed_path: data/datasets/processed/interview_questions
